apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.dev.name }}-app
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.dev.name }}-app
  template:
    metadata:
      labels:
        app: {{ .Values.dev.name }}-app
    spec:
      containers:
      - name: {{ .Values.dev.name }}-container
        image: wokanadedo4644/dev:1
        ports:
        - containerPort: 80
