apiVersion: apps/v1
kind: Deployment
metadata:
  name: prod-app
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: prod-app
  template:
    metadata:
      labels:
        app: prod-app
    spec:
      containers:
      - name: prod-container
        image: wokanadedo4644/prod:1
        ports:
        - containerPort: 80
