apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.prod.name }}-app
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.prod.name }}-app
  template:
    metadata:
      labels:
        app: {{ .Values.prod.name }}-app
    spec:
      containers:
      - name: {{ .Values.prod.name }}-container
        image: wokanadedo4644/prod:1
        ports:
        - containerPort: 80
