apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.prod.name }}-service
spec:
  selector:
    app: {{ .Values.prod.name }}-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
